/**
 * Full English grammar syllabus (A1→C1) for the /grammar catalog.
 * Drill items live separately in grammarTopics.ts and merge by slug.
 */

export type CefrBand = 1 | 2 | 3 | 4 | 5; // A1 A2 B1 B2 C1

export type CurriculumTopic = {
  slug: string;
  title: string;
  summary: string;
  tip_tr: string;
  example: string;
  difficulty: CefrBand;
  category: string;
};

export const CEFR_LABEL: Record<CefrBand, string> = {
  1: "A1",
  2: "A2",
  3: "B1",
  4: "B2",
  5: "C1",
};

export const CEFR_SECTION_TITLE: Record<CefrBand, string> = {
  1: "A1 — Temel",
  2: "A2 — Temel üstü",
  3: "B1 — Orta",
  4: "B2 — Orta üstü",
  5: "C1 — İleri",
};

/** Complete topic list shown on /grammar (order = learning path). */
export const GRAMMAR_CURRICULUM: CurriculumTopic[] = [
  // ── A1 ──────────────────────────────────────────────────────────────
  {
    slug: "be-am-is-are",
    title: "To be: am / is / are",
    summary: "Use am with I, is with he/she/it, are with you/we/they for identity, feelings, and location.",
    tip_tr: "I am · he/she/it is · you/we/they are",
    example: "I am a student. She is tired. They are at home.",
    difficulty: 1,
    category: "Verbs",
  },
  {
    slug: "subject-pronouns",
    title: "Subject pronouns",
    summary: "I, you, he, she, it, we, they replace the subject of a sentence.",
    tip_tr: "I / you / he / she / it / we / they",
    example: "Ali is here. He is here.",
    difficulty: 1,
    category: "Pronouns",
  },
  {
    slug: "possessive-adjectives",
    title: "Possessive adjectives",
    summary: "my, your, his, her, its, our, their come before a noun to show ownership.",
    tip_tr: "my book · her name · their car",
    example: "This is my bag. That is her phone.",
    difficulty: 1,
    category: "Pronouns",
  },
  {
    slug: "articles-a-an",
    title: "Articles: a / an",
    summary: "a/an = one (not specific). Use an before a vowel sound.",
    tip_tr: "a book · an apple · an hour (sesli harf sesi)",
    example: "I need a pen and an eraser.",
    difficulty: 1,
    category: "Articles",
  },
  {
    slug: "articles-a-an-the",
    title: "Articles: a / an / the",
    summary: "a/an = one (not specific). the = specific / known to speaker and listener.",
    tip_tr: "a/an = belirsiz · the = belirli",
    example: "I bought an apple and the apple was sweet.",
    difficulty: 1,
    category: "Articles",
  },
  {
    slug: "plurals",
    title: "Plural nouns",
    summary: "Most nouns add -s/-es. Watch irregular plurals (child → children, mouse → mice).",
    tip_tr: "book → books · box → boxes · child → children",
    example: "Two books, three boxes, five children.",
    difficulty: 1,
    category: "Nouns",
  },
  {
    slug: "this-that-these-those",
    title: "Demonstratives: this / that / these / those",
    summary: "this/these = near; that/those = far. this/that singular; these/those plural.",
    tip_tr: "this/these = yakın · that/those = uzak",
    example: "This book is mine. Those cars are expensive.",
    difficulty: 1,
    category: "Determiners",
  },
  {
    slug: "there-is-are",
    title: "There is / there are",
    summary: "Use there is + singular and there are + plural to say something exists.",
    tip_tr: "There is a… · There are two…",
    example: "There is a café nearby. There are many students.",
    difficulty: 1,
    category: "Structure",
  },
  {
    slug: "have-has",
    title: "Have / has",
    summary: "have with I/you/we/they; has with he/she/it for possession.",
    tip_tr: "I have · she has",
    example: "I have a bike. She has two cats.",
    difficulty: 1,
    category: "Verbs",
  },
  {
    slug: "present-simple",
    title: "Present Simple",
    summary: "Use Present Simple for habits, routines, and facts. Add -s/-es with he/she/it.",
    tip_tr: "Alışkanlık ve gerçekler: I work / she works.",
    example: "She goes to school every day.",
    difficulty: 1,
    category: "Tenses",
  },
  {
    slug: "present-simple-neg-q",
    title: "Present Simple: negatives & questions",
    summary: "Negatives and questions use do/does + base verb.",
    tip_tr: "don't/doesn't + V1 · Do/Does + özne + V1?",
    example: "She doesn't like tea. Do you live here?",
    difficulty: 1,
    category: "Tenses",
  },
  {
    slug: "present-continuous",
    title: "Present Continuous",
    summary: "Use am/is/are + verb-ing for actions happening now or around now.",
    tip_tr: "Şu an: am/is/are + V-ing",
    example: "They are playing football right now.",
    difficulty: 1,
    category: "Tenses",
  },
  {
    slug: "can-cant",
    title: "Can / can't (ability & permission)",
    summary: "can + base verb for ability or permission; can't for inability or refusal.",
    tip_tr: "can + V1 · can't = cannot",
    example: "I can swim. Can I open the window?",
    difficulty: 1,
    category: "Modals",
  },
  {
    slug: "imperatives",
    title: "Imperatives",
    summary: "Use the base verb to give orders, requests, and instructions. Don't + verb for negatives.",
    tip_tr: "Open the door. · Don't run.",
    example: "Sit down. Don't touch that.",
    difficulty: 1,
    category: "Structure",
  },
  {
    slug: "in-on-at",
    title: "Prepositions: in / on / at (place)",
    summary: "in = enclosed space; on = surface; at = exact point.",
    tip_tr: "in = içinde · on = üzerinde · at = noktada",
    example: "She is at school. The book is on the table. We live in Ankara.",
    difficulty: 1,
    category: "Prepositions",
  },
  {
    slug: "prepositions-time",
    title: "Prepositions of time",
    summary: "in + months/years/parts of day; on + days/dates; at + clock times / night.",
    tip_tr: "in July · on Monday · at 7 o'clock",
    example: "I was born in 2005. See you on Friday at 6.",
    difficulty: 1,
    category: "Prepositions",
  },
  {
    slug: "wh-questions",
    title: "Wh- questions",
    summary: "who, what, where, when, why, how ask for specific information.",
    tip_tr: "Who / What / Where / When / Why / How",
    example: "Where do you live? Why are you late?",
    difficulty: 1,
    category: "Questions",
  },
  {
    slug: "adjectives-basic",
    title: "Adjectives (basic)",
    summary: "Adjectives describe nouns and usually come before the noun or after be.",
    tip_tr: "a big house · She is happy.",
    example: "It is a cold day. The film was boring.",
    difficulty: 1,
    category: "Adjectives",
  },
  {
    slug: "adverbs-frequency",
    title: "Adverbs of frequency",
    summary: "always, usually, often, sometimes, rarely, never usually go before the main verb (after be).",
    tip_tr: "always → never · be'den sonra, diğer fiilden önce",
    example: "She always arrives early. He is never late.",
    difficulty: 1,
    category: "Adverbs",
  },
  {
    slug: "object-pronouns",
    title: "Object pronouns",
    summary: "me, you, him, her, it, us, them replace the object of a verb or preposition.",
    tip_tr: "me / him / her / us / them",
    example: "Call me. I saw them yesterday.",
    difficulty: 1,
    category: "Pronouns",
  },
  {
    slug: "possessive-s",
    title: "Possessive 's",
    summary: "Add 's to a person/animal to show ownership. Plural ending in s takes only '.",
    tip_tr: "Ali's bag · the students' books",
    example: "This is Sara's phone. The boys' room is tidy.",
    difficulty: 1,
    category: "Nouns",
  },
  {
    slug: "possessive-pronouns",
    title: "Possessive pronouns",
    summary: "mine, yours, his, hers, ours, theirs replace a noun phrase (not followed by a noun).",
    tip_tr: "This is mine. · That bag is hers. (my book ≠ mine)",
    example: "Is this pen yours? No, it's mine.",
    difficulty: 1,
    category: "Pronouns",
  },
  {
    slug: "have-got",
    title: "Have got / has got",
    summary: "have got = have (possession), common in British English; questions with have…got?",
    tip_tr: "I've got · she's got · Have you got…?",
    example: "I've got two brothers. Has she got a car?",
    difficulty: 1,
    category: "Verbs",
  },
  {
    slug: "be-questions-short-answers",
    title: "Be: questions & short answers",
    summary: "Invert be for yes/no questions; answer with Yes/No + pronoun + be (not the full verb).",
    tip_tr: "Are you ready? — Yes, I am. / No, I'm not.",
    example: "Is she a teacher? Yes, she is.",
    difficulty: 1,
    category: "Questions",
  },
  {
    slug: "and-but-or-because",
    title: "And / but / or / because",
    summary: "Basic conjunctions join ideas: and (add), but (contrast), or (choice), because (reason).",
    tip_tr: "and · but · or · because",
    example: "I stayed home because it rained.",
    difficulty: 1,
    category: "Conjunctions",
  },
  {
    slug: "like-love-hate-ing",
    title: "Like / love / hate + -ing",
    summary: "After like, love, enjoy, hate, prefer use verb-ing for general preferences.",
    tip_tr: "like + V-ing · I love swimming.",
    example: "She hates getting up early. We enjoy cooking.",
    difficulty: 1,
    category: "Verbs",
  },
  {
    slug: "want-need-would-like",
    title: "Want / need / would like + to",
    summary: "want/need/would like + to + verb for desires and needs; would like is more polite.",
    tip_tr: "want to go · need to study · I'd like to…",
    example: "I want to learn English. I'd like to order tea.",
    difficulty: 1,
    category: "Verbs",
  },
  {
    slug: "prepositions-movement",
    title: "Prepositions of movement",
    summary: "to, from, into, out of, onto, off, through, across, along describe direction.",
    tip_tr: "to school · into the room · across the street",
    example: "She walked into the café. He ran across the park.",
    difficulty: 1,
    category: "Prepositions",
  },
  {
    slug: "how-much-how-many",
    title: "How much / how many",
    summary: "how many + countable plural; how much + uncountable (and for price).",
    tip_tr: "How many books? · How much water/money?",
    example: "How many students are there? How much is it?",
    difficulty: 1,
    category: "Questions",
  },
  {
    slug: "whose",
    title: "Whose",
    summary: "whose asks about ownership; answer with possessive adjective/pronoun or 's.",
    tip_tr: "Whose bag is this? — It's Ali's. / It's mine.",
    example: "Whose phone is ringing?",
    difficulty: 1,
    category: "Questions",
  },
  {
    slug: "lets-suggestions",
    title: "Let's / shall we (suggestions)",
    summary: "Let's + verb suggests doing something together; Shall we…? is a polite alternative.",
    tip_tr: "Let's go. · Shall we start?",
    example: "Let's watch a film. Shall we meet at 6?",
    difficulty: 1,
    category: "Structure",
  },
  {
    slug: "present-simple-vs-continuous",
    title: "Present Simple vs Continuous",
    summary: "Habits/facts → Present Simple. Happening now / temporary → Present Continuous.",
    tip_tr: "every day → Simple · now/at the moment → Continuous",
    example: "I usually walk, but today I'm taking the bus.",
    difficulty: 1,
    category: "Tenses",
  },
  {
    slug: "stative-verbs",
    title: "Stative verbs",
    summary: "Know, like, want, believe, own… describe states and are rarely used in continuous forms.",
    tip_tr: "I know (not I'm knowing) · I want / I like / I believe",
    example: "I understand the rule. She owns a flat in Izmir.",
    difficulty: 1,
    category: "Verbs",
  },
  {
    slug: "prepositions-place-extra",
    title: "Prepositions of place (next to / between…)",
    summary: "next to, between, opposite, behind, in front of, under, above, near describe position.",
    tip_tr: "next to · between · opposite · behind · in front of",
    example: "The bank is opposite the park, next to the café.",
    difficulty: 1,
    category: "Prepositions",
  },
  {
    slug: "by-transport",
    title: "By / on (transport)",
    summary: "by + means of transport (by bus/car/train); on foot; on the bus/train when inside.",
    tip_tr: "by bus · by car · on foot · on the train",
    example: "I go to work by metro. We came on foot.",
    difficulty: 1,
    category: "Prepositions",
  },
  {
    slug: "telling-the-time",
    title: "Telling the time",
    summary: "o'clock, half past, quarter past/to; at + clock time; a.m./p.m. or 24-hour style.",
    tip_tr: "at 7 o'clock · half past two · quarter to nine",
    example: "The class starts at half past nine.",
    difficulty: 1,
    category: "Structure",
  },

  // ── A2 ──────────────────────────────────────────────────────────────
  {
    slug: "past-simple",
    title: "Past Simple",
    summary: "Use Past Simple for finished actions in the past. Regular verbs take -ed; many are irregular.",
    tip_tr: "Bitmiş geçmiş: V2 (worked / went)",
    example: "I watched a movie last night.",
    difficulty: 2,
    category: "Tenses",
  },
  {
    slug: "past-simple-irregular",
    title: "Past Simple: irregular verbs",
    summary: "Common irregulars: go→went, see→saw, have→had, make→made, take→took.",
    tip_tr: "go–went · see–saw · take–took · make–made",
    example: "She went home. He took the bus.",
    difficulty: 2,
    category: "Tenses",
  },
  {
    slug: "past-continuous",
    title: "Past Continuous",
    summary: "was/were + V-ing for an action in progress at a past moment (often interrupted).",
    tip_tr: "was/were + V-ing",
    example: "I was cooking when she called.",
    difficulty: 2,
    category: "Tenses",
  },
  {
    slug: "going-to",
    title: "Future: be going to",
    summary: "am/is/are + going to + verb for plans and predictions from present evidence.",
    tip_tr: "be + going to + V1",
    example: "I'm going to study tonight. Look at those clouds — it's going to rain.",
    difficulty: 2,
    category: "Tenses",
  },
  {
    slug: "will-future",
    title: "Future: will",
    summary: "will + base verb for instant decisions, offers, promises, and predictions.",
    tip_tr: "will + V1 · won't = will not",
    example: "I'll help you. It will be sunny tomorrow.",
    difficulty: 2,
    category: "Tenses",
  },
  {
    slug: "present-continuous-future",
    title: "Present Continuous for future",
    summary: "am/is/are + V-ing for fixed personal arrangements in the near future.",
    tip_tr: "Yarınki randevu: I'm meeting Ali at 5.",
    example: "We're flying to Izmir on Friday.",
    difficulty: 2,
    category: "Tenses",
  },
  {
    slug: "present-perfect",
    title: "Present Perfect",
    summary: "have/has + past participle for life experience and actions linked to now (for/since).",
    tip_tr: "have/has + V3 · for / since",
    example: "She has lived in London since 2010.",
    difficulty: 2,
    category: "Tenses",
  },
  {
    slug: "present-perfect-vs-past",
    title: "Present Perfect vs Past Simple",
    summary: "Present Perfect = unfinished time / result now. Past Simple = finished time (yesterday, in 2019).",
    tip_tr: "ever/never/just → Perfect · yesterday/last… → Past",
    example: "I have seen that film. I saw it last week.",
    difficulty: 2,
    category: "Tenses",
  },
  {
    slug: "comparatives",
    title: "Comparatives",
    summary: "Compare two things: adj + -er + than, or more + adj + than for longer adjectives.",
    tip_tr: "taller than · more interesting than · better/worse",
    example: "This bag is cheaper than that one.",
    difficulty: 2,
    category: "Adjectives",
  },
  {
    slug: "superlatives",
    title: "Superlatives",
    summary: "the + adj-est or the most + adj to say something is number one in a group.",
    tip_tr: "the tallest · the most expensive · the best",
    example: "She is the fastest runner in the class.",
    difficulty: 2,
    category: "Adjectives",
  },
  {
    slug: "countable-uncountable",
    title: "Countable & uncountable nouns",
    summary: "Countable have singular/plural (a book / books). Uncountable have no plural (water, advice, information).",
    tip_tr: "a/an/many + sayıla bilir · much/some + sayılamaz",
    example: "I need some water and two apples.",
    difficulty: 2,
    category: "Nouns",
  },
  {
    slug: "some-any-much-many",
    title: "Some / any / much / many",
    summary: "some (positive), any (questions/negatives); many + countable, much + uncountable.",
    tip_tr: "some (+) · any (?/–) · many books · much time",
    example: "Do you have any sugar? I don't have much time.",
    difficulty: 2,
    category: "Quantifiers",
  },
  {
    slug: "modals-obligation",
    title: "Must / have to / should",
    summary: "must/have to = obligation; should = advice; mustn't = prohibition; don't have to = no need.",
    tip_tr: "must/have to = zorunluluk · should = tavsiye",
    example: "You should sleep more. You mustn't smoke here.",
    difficulty: 2,
    category: "Modals",
  },
  {
    slug: "could-would",
    title: "Could / would",
    summary: "could = past ability / polite request; would like = polite want; would = hypothetical.",
    tip_tr: "Could you…? · I'd like… · I could swim (geçmiş)",
    example: "Could you help me? I'd like a coffee.",
    difficulty: 2,
    category: "Modals",
  },
  {
    slug: "first-conditional",
    title: "First conditional",
    summary: "If + Present Simple, will + verb for real future possibilities.",
    tip_tr: "If it rains, I will stay home.",
    example: "If you study, you will pass.",
    difficulty: 2,
    category: "Conditionals",
  },
  {
    slug: "gerunds-infinitives",
    title: "Gerunds & infinitives",
    summary: "Some verbs take -ing (enjoy swimming); others take to + verb (want to go).",
    tip_tr: "enjoy + V-ing · want + to V",
    example: "I enjoy reading. She wants to travel.",
    difficulty: 2,
    category: "Verbs",
  },
  {
    slug: "relative-who-which",
    title: "Relative pronouns: who / which / that",
    summary: "who = people; which = things; that = people or things in defining clauses.",
    tip_tr: "who = kişi · which = şey · that = ikisi",
    example: "The man who called is my teacher.",
    difficulty: 2,
    category: "Clauses",
  },
  {
    slug: "articles-the",
    title: "Articles: the (specific use)",
    summary: "the for unique things, second mention, superlatives, and known shared context.",
    tip_tr: "the sun · the first one · the same café",
    example: "The moon is bright tonight.",
    difficulty: 2,
    category: "Articles",
  },
  {
    slug: "adverbs-manner",
    title: "Adverbs of manner",
    summary: "Many adverbs add -ly to adjectives (quick → quickly) and say how something happens.",
    tip_tr: "slow → slowly · careful → carefully · fast/hard (aynı)",
    example: "She speaks English clearly.",
    difficulty: 2,
    category: "Adverbs",
  },
  {
    slug: "used-to",
    title: "Used to",
    summary: "used to + verb for past habits or states that are no longer true.",
    tip_tr: "used to + V1 (eskiden … yapardım)",
    example: "I used to play tennis every week.",
    difficulty: 2,
    category: "Tenses",
  },
  {
    slug: "past-simple-vs-continuous",
    title: "Past Simple vs Continuous",
    summary: "Past Continuous = background/in progress; Past Simple = finished interrupting action.",
    tip_tr: "I was reading when the phone rang.",
    example: "While she was cooking, he set the table.",
    difficulty: 2,
    category: "Tenses",
  },
  {
    slug: "will-vs-going-to",
    title: "Will vs be going to",
    summary: "going to = plan/evidence; will = instant decision, offer, promise, or general prediction.",
    tip_tr: "plan → going to · karar anı/teklif → will",
    example: "I'm going to visit Mum. Oh, I'll come too!",
    difficulty: 2,
    category: "Tenses",
  },
  {
    slug: "zero-conditional",
    title: "Zero conditional",
    summary: "If + Present, Present for facts and general truths (always true).",
    tip_tr: "If you heat ice, it melts.",
    example: "If people don't drink water, they get thirsty.",
    difficulty: 2,
    category: "Conditionals",
  },
  {
    slug: "indefinite-pronouns",
    title: "Someone / anyone / nothing…",
    summary: "someone/anyone/everyone/no one; something/anything…; somewhere/anywhere…",
    tip_tr: "someone (+) · anyone (?/–) · nothing = not anything",
    example: "Someone called. I didn't see anyone. There's nothing here.",
    difficulty: 2,
    category: "Pronouns",
  },
  {
    slug: "reflexive-pronouns",
    title: "Reflexive pronouns",
    summary: "myself, yourself, himself… when subject and object are the same; also for emphasis.",
    tip_tr: "myself / yourself / themselves · by myself = alone",
    example: "She hurt herself. I fixed it myself.",
    difficulty: 2,
    category: "Pronouns",
  },
  {
    slug: "each-other",
    title: "Each other / one another",
    summary: "each other (and one another) for reciprocal actions between two or more people.",
    tip_tr: "They help each other.",
    example: "We send each other messages every day.",
    difficulty: 2,
    category: "Pronouns",
  },
  {
    slug: "adjective-prepositions",
    title: "Adjective + preposition",
    summary: "Fixed pairs: good at, interested in, afraid of, famous for, similar to, different from.",
    tip_tr: "good at · interested in · afraid of · keen on",
    example: "She's good at maths. I'm interested in history.",
    difficulty: 2,
    category: "Prepositions",
  },
  {
    slug: "verb-prepositions",
    title: "Verb + preposition",
    summary: "listen to, wait for, depend on, look for, belong to, talk about — learn as chunks.",
    tip_tr: "listen to · wait for · look for · belong to",
    example: "I'm waiting for the bus. It depends on the weather.",
    difficulty: 2,
    category: "Prepositions",
  },
  {
    slug: "already-yet-just-still",
    title: "Already / yet / just / still",
    summary: "just/already often with Present Perfect; yet in questions/negatives; still = continuing.",
    tip_tr: "just/already · yet (?/–) · still (hâlâ)",
    example: "I've just finished. Have you eaten yet? She's still working.",
    difficulty: 2,
    category: "Adverbs",
  },
  {
    slug: "ago",
    title: "Ago",
    summary: "ago goes after a past time period and is used with Past Simple (not Present Perfect).",
    tip_tr: "two days ago · (Present Perfect ile kullanılmaz)",
    example: "I met her three years ago.",
    difficulty: 2,
    category: "Adverbs",
  },
  {
    slug: "may-might",
    title: "May / might",
    summary: "may/might + verb = possibility; may also for polite permission.",
    tip_tr: "might rain · May I sit here?",
    example: "It might snow later. You may leave early.",
    difficulty: 2,
    category: "Modals",
  },
  {
    slug: "question-tags",
    title: "Question tags",
    summary: "Short tags (isn't it?, don't you?) check or confirm; polarity usually opposite to the statement.",
    tip_tr: "You're tired, aren't you? · She doesn't drive, does she?",
    example: "It's cold, isn't it? Let's go, shall we?",
    difficulty: 2,
    category: "Questions",
  },
  {
    slug: "make-vs-do",
    title: "Make vs do",
    summary: "do = tasks/activities (homework, exercise); make = create/produce (a cake, a decision, a mistake).",
    tip_tr: "do homework · make a cake / a mistake",
    example: "I did the washing-up. She made a reservation.",
    difficulty: 2,
    category: "Vocabulary",
  },
  {
    slug: "say-vs-tell",
    title: "Say vs tell",
    summary: "tell needs a person (tell me); say focuses on the words (say that… / say to someone).",
    tip_tr: "tell someone · say something (to someone)",
    example: "She told me the truth. He said he was busy.",
    difficulty: 2,
    category: "Vocabulary",
  },
  {
    slug: "adverbs-degree",
    title: "Adverbs of degree",
    summary: "very, really, quite, a bit, too modify adjectives and other adverbs.",
    tip_tr: "very tired · quite good · a bit late",
    example: "The exam was really hard. It's quite warm today.",
    difficulty: 2,
    category: "Adverbs",
  },
  {
    slug: "adjective-order",
    title: "Adjective order",
    summary: "Opinion before fact; typical order: opinion → size → age → colour → origin → material → purpose.",
    tip_tr: "a lovely small old red Italian leather bag",
    example: "She bought a beautiful new black dress.",
    difficulty: 2,
    category: "Adjectives",
  },
  {
    slug: "as-as-equality",
    title: "As… as (equality)",
    summary: "as + adjective/adverb + as for equal comparison; not as/so… as for inequality.",
    tip_tr: "as tall as · not as expensive as",
    example: "She is as tall as her brother. This isn't as hard as I thought.",
    difficulty: 2,
    category: "Adjectives",
  },
  {
    slug: "comparative-adverbs",
    title: "Comparative adverbs",
    summary: "Compare how actions happen: -er / more + adverb + than; irregular: better, worse, further.",
    tip_tr: "faster than · more carefully · better/worse",
    example: "She drives more carefully than I do.",
    difficulty: 2,
    category: "Adverbs",
  },
  {
    slug: "during-for-while",
    title: "During / for / while",
    summary: "during + noun; for + period; while + clause (action in progress).",
    tip_tr: "during the lesson · for two hours · while I was cooking",
    example: "I slept during the film. I waited for an hour while she shopped.",
    difficulty: 2,
    category: "Prepositions",
  },
  {
    slug: "by-vs-until",
    title: "By vs until",
    summary: "by = not later than a deadline; until/till = up to a point, then stopping.",
    tip_tr: "by Friday = en geç · until Friday = Cuma'ya kadar",
    example: "Finish it by Monday. I'll stay until 6.",
    difficulty: 2,
    category: "Prepositions",
  },
  {
    slug: "like-vs-as",
    title: "Like vs as",
    summary: "like + noun = similar to; as + noun = in the role of; as + clause also for manner.",
    tip_tr: "She sings like a bird. · He works as a teacher.",
    example: "Do it as I showed you. It looks like rain.",
    difficulty: 2,
    category: "Prepositions",
  },
  {
    slug: "ed-ing-adjectives",
    title: "-ed / -ing adjectives",
    summary: "-ing describes the cause (boring film); -ed describes the feeling (bored students).",
    tip_tr: "interesting / interested · boring / bored · tiring / tired",
    example: "The lesson was interesting. The students were interested.",
    difficulty: 2,
    category: "Adjectives",
  },
  {
    slug: "mustnt-vs-dont-have-to",
    title: "Mustn't vs don't have to",
    summary: "mustn't = prohibition; don't have to / needn't = no obligation (you can if you want).",
    tip_tr: "mustn't = yasak · don't have to = gerek yok",
    example: "You mustn't park here. You don't have to come if you're busy.",
    difficulty: 2,
    category: "Modals",
  },
  {
    slug: "shall",
    title: "Shall (offers & suggestions)",
    summary: "Shall I…? offers help; Shall we…? suggests; mainly British English, first person.",
    tip_tr: "Shall I open the window? · Shall we dance?",
    example: "Shall I carry that bag for you?",
    difficulty: 2,
    category: "Modals",
  },
  {
    slug: "get-passive-basic",
    title: "Get + adjective / get + V3",
    summary: "get + adjective = become; get + past participle = informal passive / change of state.",
    tip_tr: "get tired · get married · get stolen (günlük)",
    example: "I'm getting hungry. My phone got stolen.",
    difficulty: 2,
    category: "Verbs",
  },

  // ── B1 ──────────────────────────────────────────────────────────────
  {
    slug: "present-perfect-continuous",
    title: "Present Perfect Continuous",
    summary: "have/has been + V-ing for actions that started in the past and continue, or just stopped with a visible result.",
    tip_tr: "have/has been + V-ing",
    example: "I have been waiting for an hour.",
    difficulty: 3,
    category: "Tenses",
  },
  {
    slug: "past-perfect",
    title: "Past Perfect",
    summary: "had + V3 for an action completed before another past action.",
    tip_tr: "had + V3 (önce bitmiş geçmiş)",
    example: "She had left before I arrived.",
    difficulty: 3,
    category: "Tenses",
  },
  {
    slug: "past-perfect-continuous",
    title: "Past Perfect Continuous",
    summary: "had been + V-ing for a continuous action before a past point.",
    tip_tr: "had been + V-ing",
    example: "He had been working all day before the meeting.",
    difficulty: 3,
    category: "Tenses",
  },
  {
    slug: "future-continuous",
    title: "Future Continuous",
    summary: "will be + V-ing for an action in progress at a future time.",
    tip_tr: "will be + V-ing",
    example: "This time tomorrow I will be flying to Rome.",
    difficulty: 3,
    category: "Tenses",
  },
  {
    slug: "future-perfect",
    title: "Future Perfect",
    summary: "will have + V3 for an action completed before a future deadline.",
    tip_tr: "will have + V3",
    example: "By Friday I will have finished the report.",
    difficulty: 3,
    category: "Tenses",
  },
  {
    slug: "second-conditional",
    title: "Second conditional",
    summary: "If + Past Simple, would + verb for unreal or unlikely present/future situations.",
    tip_tr: "If I were rich, I would travel.",
    example: "If I had more time, I would learn piano.",
    difficulty: 3,
    category: "Conditionals",
  },
  {
    slug: "third-conditional",
    title: "Third conditional",
    summary: "If + Past Perfect, would have + V3 for unreal past (regret / different past).",
    tip_tr: "If I had studied, I would have passed.",
    example: "If she had left earlier, she would have caught the train.",
    difficulty: 3,
    category: "Conditionals",
  },
  {
    slug: "passive-voice",
    title: "Passive voice",
    summary: "be + V3 when the focus is on the action/result, not the doer (by + agent optional).",
    tip_tr: "be + V3 · The letter was sent.",
    example: "English is spoken here. The cake was made by Tom.",
    difficulty: 3,
    category: "Voice",
  },
  {
    slug: "reported-speech",
    title: "Reported speech",
    summary: "Backshift tenses when reporting past statements; change pronouns and time words.",
    tip_tr: "am → was · will → would · today → that day",
    example: "She said she was tired. He told me he would call.",
    difficulty: 3,
    category: "Speech",
  },
  {
    slug: "relative-clauses",
    title: "Relative clauses",
    summary: "Defining clauses identify the noun; non-defining add extra info and use commas.",
    tip_tr: "tanımlayan (virgülsüz) · ek bilgi (virgüllü)",
    example: "My brother, who lives in Berlin, is a doctor.",
    difficulty: 3,
    category: "Clauses",
  },
  {
    slug: "modals-deduction",
    title: "Modals of deduction",
    summary: "must = certainty; might/may/could = possibility; can't = impossibility (about now).",
    tip_tr: "must be · might be · can't be",
    example: "He must be at work. That can't be true.",
    difficulty: 3,
    category: "Modals",
  },
  {
    slug: "wish-if-only",
    title: "Wish / if only",
    summary: "wish + Past Simple (present regret); wish + Past Perfect (past regret); wish + would (annoyance).",
    tip_tr: "I wish I knew · I wish I had gone",
    example: "I wish I spoke French. If only I had listened.",
    difficulty: 3,
    category: "Structure",
  },
  {
    slug: "so-such",
    title: "So / such",
    summary: "so + adjective/adverb; such + (a/an) + adjective + noun for emphasis.",
    tip_tr: "so tired · such a long day",
    example: "It was so cold. It was such a cold night.",
    difficulty: 3,
    category: "Intensifiers",
  },
  {
    slug: "enough-too",
    title: "Enough / too",
    summary: "too = more than wanted; enough = as much as needed (adj + enough / enough + noun).",
    tip_tr: "too heavy · tall enough · enough money",
    example: "This bag is too heavy. I'm not tall enough.",
    difficulty: 3,
    category: "Quantifiers",
  },
  {
    slug: "both-either-neither",
    title: "Both / either / neither",
    summary: "both = the two; either = one or the other; neither = not one and not the other.",
    tip_tr: "both of them · either option · neither works",
    example: "Both answers are correct. Neither team scored.",
    difficulty: 3,
    category: "Determiners",
  },
  {
    slug: "quantifiers",
    title: "Quantifiers (few / little / plenty)",
    summary: "a few/few + countable; a little/little + uncountable; plenty of = more than enough.",
    tip_tr: "a few friends · little time · plenty of food",
    example: "I have a few ideas but little money.",
    difficulty: 3,
    category: "Quantifiers",
  },
  {
    slug: "linking-words",
    title: "Linking words",
    summary: "although, however, therefore, because, so, while connect ideas logically.",
    tip_tr: "although / however / therefore / because",
    example: "Although it rained, we went out.",
    difficulty: 3,
    category: "Discourse",
  },
  {
    slug: "phrasal-verbs",
    title: "Phrasal verbs",
    summary: "Verb + particle with a special meaning (look up, give up, turn on). Some are separable.",
    tip_tr: "look up · give up · turn on (ayrılabilir olanlar)",
    example: "Please turn the lights off. She gave up smoking.",
    difficulty: 3,
    category: "Vocabulary",
  },
  {
    slug: "be-used-to-get-used-to",
    title: "Be used to / get used to",
    summary: "be used to + noun/-ing = accustomed; get used to = becoming accustomed (≠ used to + V1).",
    tip_tr: "I'm used to waking early. · I'm getting used to it.",
    example: "She's used to the noise. You'll get used to driving here.",
    difficulty: 3,
    category: "Structure",
  },
  {
    slug: "time-clauses",
    title: "Time clauses (when / until / as soon as…)",
    summary: "when, while, before, after, until, as soon as, once + Present for future time (not will).",
    tip_tr: "When I arrive, I'll call. (will yok yan cümlede)",
    example: "I'll wait until she finishes. Call me as soon as you land.",
    difficulty: 3,
    category: "Clauses",
  },
  {
    slug: "purpose-clauses",
    title: "Purpose: to / in order to / so that",
    summary: "to / in order to / so as to + verb; so that + clause (often with can/will).",
    tip_tr: "to learn · in order to pass · so that I can…",
    example: "I study to improve. I left early so that I wouldn't be late.",
    difficulty: 3,
    category: "Clauses",
  },
  {
    slug: "contrast-clauses",
    title: "Contrast: although / despite / while",
    summary: "although/even though + clause; despite/in spite of + noun/-ing; while/whereas for contrast.",
    tip_tr: "although it rained · despite the rain · whereas",
    example: "Although he was tired, he continued. Despite the rain, we went out.",
    difficulty: 3,
    category: "Clauses",
  },
  {
    slug: "prefer-would-rather",
    title: "Prefer / would rather",
    summary: "prefer A to B; would rather + base verb; would prefer to + verb.",
    tip_tr: "prefer tea to coffee · I'd rather stay · I'd prefer to go",
    example: "I'd rather walk than take a taxi.",
    difficulty: 3,
    category: "Verbs",
  },
  {
    slug: "indirect-questions",
    title: "Indirect questions",
    summary: "Polite questions keep statement word order after if/whether or a wh- word (no do-support).",
    tip_tr: "Could you tell me where the station is? (is the station değil)",
    example: "Do you know if she's coming? I wonder what time it starts.",
    difficulty: 3,
    category: "Questions",
  },
  {
    slug: "another-other-others",
    title: "Another / other / others / the other",
    summary: "another + singular; other + plural/uncountable; others = other ones; the other = the remaining.",
    tip_tr: "another day · other people · the other one · others",
    example: "I need another pen. Where are the others?",
    difficulty: 3,
    category: "Determiners",
  },
  {
    slug: "each-every-all-whole",
    title: "Each / every / all / whole",
    summary: "each/every + singular; all + plural/uncountable; whole/entire often with the + singular noun.",
    tip_tr: "each student · every day · all the time · the whole day",
    example: "Every child needs care. We spent the whole weekend studying.",
    difficulty: 3,
    category: "Determiners",
  },
  {
    slug: "so-neither-agreement",
    title: "So / neither (agreement)",
    summary: "So do I / Neither do I to agree with positive/negative statements; invert auxiliary + subject.",
    tip_tr: "So do I. · Neither have I. · Me too / Me neither (günlük)",
    example: "I love jazz. — So do I. I don't eat meat. — Neither do I.",
    difficulty: 3,
    category: "Structure",
  },
  {
    slug: "its-time",
    title: "It's time / it's high time",
    summary: "It's time + to-infinitive, or It's (high) time + Past Simple for overdue action.",
    tip_tr: "It's time to go. · It's time we left.",
    example: "It's high time you started revising.",
    difficulty: 3,
    category: "Structure",
  },
  {
    slug: "verbs-of-perception",
    title: "Verbs of perception",
    summary: "see/hear/watch/feel + object + bare infinitive (complete) or -ing (in progress).",
    tip_tr: "I saw her leave. · I saw her leaving.",
    example: "I heard him sing. I heard him singing in the shower.",
    difficulty: 3,
    category: "Verbs",
  },
  {
    slug: "look-forward-to",
    title: "Look forward to + -ing",
    summary: "look forward to is a fixed phrase; to is a preposition, so use noun or -ing (not infinitive).",
    tip_tr: "look forward to seeing you (to + V-ing)",
    example: "I'm looking forward to meeting your family.",
    difficulty: 3,
    category: "Verbs",
  },
  {
    slug: "had-better",
    title: "Had better",
    summary: "had better + base verb for strong advice/warning about now or the near future.",
    tip_tr: "you'd better go · you'd better not be late",
    example: "You'd better take an umbrella. It looks like rain.",
    difficulty: 3,
    category: "Modals",
  },
  {
    slug: "for-since",
    title: "For / since",
    summary: "for + period (for two years); since + starting point (since 2020 / since Monday).",
    tip_tr: "for = süre · since = başlangıç noktası",
    example: "I've lived here for five years / since 2019.",
    difficulty: 3,
    category: "Prepositions",
  },
  {
    slug: "present-perfect-vs-continuous",
    title: "Present Perfect vs Perfect Continuous",
    summary: "Simple Perfect often focuses on result/amount; Continuous on duration/activity itself.",
    tip_tr: "I've written three emails. · I've been writing all morning.",
    example: "She's read the book. She's been reading for hours.",
    difficulty: 3,
    category: "Tenses",
  },
  {
    slug: "gerunds-infinitives-change",
    title: "Gerund vs infinitive (meaning change)",
    summary: "stop/remember/forget/try/regret change meaning with -ing vs to-infinitive.",
    tip_tr: "stop smoking ≠ stop to smoke · remember doing ≠ remember to do",
    example: "I stopped to buy water. I stopped buying water.",
    difficulty: 3,
    category: "Verbs",
  },
  {
    slug: "verb-object-infinitive",
    title: "Verb + object + to-infinitive",
    summary: "want/ask/tell/advise/allow/expect + object + to + verb.",
    tip_tr: "want someone to… · tell someone to… · allow someone to…",
    example: "She asked me to wait. They allowed us to leave early.",
    difficulty: 3,
    category: "Verbs",
  },
  {
    slug: "make-let-help",
    title: "Make / let / help + infinitive",
    summary: "make/let + object + bare infinitive; help + bare or to-infinitive.",
    tip_tr: "make me do · let me go · help me (to) carry",
    example: "The teacher made us rewrite it. Let me explain.",
    difficulty: 3,
    category: "Verbs",
  },
  {
    slug: "would-past-habits",
    title: "Would for past habits",
    summary: "would + verb for typical past behaviour (like used to), but not usually for past states.",
    tip_tr: "Every summer we would go camping. (durum için used to)",
    example: "On Sundays he would visit his grandparents.",
    difficulty: 3,
    category: "Tenses",
  },
  {
    slug: "probability-adverbs",
    title: "Probability adverbs",
    summary: "certainly, probably, possibly, definitely, maybe/perhaps place before the main verb (after be).",
    tip_tr: "She'll probably come. · He's definitely right.",
    example: "They will certainly win. Maybe she's late.",
    difficulty: 3,
    category: "Adverbs",
  },
  {
    slug: "reason-clauses",
    title: "Reason: because / as / since",
    summary: "because (strong reason); as/since often for known reasons, sometimes more formal.",
    tip_tr: "because · as · since (= çünkü)",
    example: "As it was late, we took a taxi. Since you're here, let's start.",
    difficulty: 3,
    category: "Clauses",
  },
  {
    slug: "so-that-result",
    title: "So… that / such… that (result)",
    summary: "so + adj/adv + that; such + (a/an) + adj + noun + that express result.",
    tip_tr: "so tired that… · such a good film that…",
    example: "It was so cold that the lake froze.",
    difficulty: 3,
    category: "Clauses",
  },

  // ── B2 ──────────────────────────────────────────────────────────────
  {
    slug: "mixed-conditionals",
    title: "Mixed conditionals",
    summary: "Mix past and present unreal forms: past cause → present result, or present condition → past result.",
    tip_tr: "If I had…, I would be… (geçmiş → şimdi)",
    example: "If I had studied medicine, I would be a doctor now.",
    difficulty: 4,
    category: "Conditionals",
  },
  {
    slug: "causative",
    title: "Causative: have / get something done",
    summary: "have/get + object + V3 when someone else does the action for you.",
    tip_tr: "have/get + nesne + V3",
    example: "I had my hair cut. She got her car repaired.",
    difficulty: 4,
    category: "Structure",
  },
  {
    slug: "advanced-passive",
    title: "Advanced passive",
    summary: "Passive with modals, reporting verbs (it is said that…), and get-passive.",
    tip_tr: "It is said that… · The window got broken.",
    example: "It is believed that the company will expand.",
    difficulty: 4,
    category: "Voice",
  },
  {
    slug: "reported-questions",
    title: "Reported questions & commands",
    summary: "No do-support; use if/whether for yes-no; ask/tell + object + to-infinitive for commands.",
    tip_tr: "He asked where I lived. · She told me to wait.",
    example: "She asked if I was ready. He told us to sit down.",
    difficulty: 4,
    category: "Speech",
  },
  {
    slug: "modals-perfect",
    title: "Modals + perfect infinitive",
    summary: "must/might/should/could + have + V3 for past deduction, advice, and possibility.",
    tip_tr: "must have · should have · could have",
    example: "You should have called. He must have forgotten.",
    difficulty: 4,
    category: "Modals",
  },
  {
    slug: "future-in-the-past",
    title: "Future in the past",
    summary: "was/were going to, would, was about to for planned or expected future from a past viewpoint.",
    tip_tr: "was going to · would · was about to",
    example: "I was going to call, but my phone died.",
    difficulty: 4,
    category: "Tenses",
  },
  {
    slug: "participle-clauses",
    title: "Participle clauses",
    summary: "Use -ing / -ed clauses to shorten relative or adverbial clauses.",
    tip_tr: "Walking home, I met Ali. · Built in 1900,…",
    example: "Feeling tired, she went to bed early.",
    difficulty: 4,
    category: "Clauses",
  },
  {
    slug: "relative-advanced",
    title: "Advanced relative clauses",
    summary: "whose, where, when, why; preposition + which/whom; reduced relatives.",
    tip_tr: "whose · of which · the man I met",
    example: "The woman whose car was stolen called the police.",
    difficulty: 4,
    category: "Clauses",
  },
  {
    slug: "inversion-conditionals",
    title: "Inversion in conditionals",
    summary: "Formal: Had I known… / Were I you… / Should you need… instead of if-clauses.",
    tip_tr: "Had I known… = If I had known…",
    example: "Had I known, I would have helped.",
    difficulty: 4,
    category: "Conditionals",
  },
  {
    slug: "cleft-sentences",
    title: "Cleft sentences",
    summary: "It is/was … that/who and What … is/was to emphasize one part of a sentence.",
    tip_tr: "It was Ali who called. · What I need is rest.",
    example: "It was yesterday that we met.",
    difficulty: 4,
    category: "Emphasis",
  },
  {
    slug: "discourse-markers",
    title: "Discourse markers",
    summary: "anyway, actually, on the other hand, in contrast, furthermore structure spoken and written argument.",
    tip_tr: "however · furthermore · on the other hand",
    example: "On the other hand, costs may rise.",
    difficulty: 4,
    category: "Discourse",
  },
  {
    slug: "noun-phrases",
    title: "Complex noun phrases",
    summary: "Stack determiners, adjectives, and of-phrases to pack information into one noun group.",
    tip_tr: "the sudden rise in prices · a well-known expert",
    example: "The rapid growth of online shopping surprised analysts.",
    difficulty: 4,
    category: "Nouns",
  },
  {
    slug: "future-perfect-continuous",
    title: "Future Perfect Continuous",
    summary: "will have been + V-ing for duration up to a future point.",
    tip_tr: "will have been + V-ing",
    example: "By June I will have been working here for five years.",
    difficulty: 4,
    category: "Tenses",
  },
  {
    slug: "narrative-tenses",
    title: "Narrative tenses",
    summary: "Combine Past Simple, Continuous, Perfect, and Perfect Continuous to tell a story clearly.",
    tip_tr: "olay = Past Simple · arka plan = Continuous · önce = Perfect",
    example: "I had been waiting when the train finally arrived.",
    difficulty: 4,
    category: "Tenses",
  },
  {
    slug: "as-if-as-though",
    title: "As if / as though",
    summary: "as if/as though introduce unreal or seeming situations; often Past for present unreality.",
    tip_tr: "He talks as if he knew everything.",
    example: "She looked as though she had seen a ghost.",
    difficulty: 4,
    category: "Clauses",
  },
  {
    slug: "whatever-whoever",
    title: "Whatever / whoever / wherever…",
    summary: "wh-ever words mean 'any…' or 'it doesn't matter which/who/where'.",
    tip_tr: "whatever · whoever · wherever · whenever · however",
    example: "Wherever you go, take a map. Call me whenever you need help.",
    difficulty: 4,
    category: "Clauses",
  },
  {
    slug: "correlative-conjunctions",
    title: "Not only… but also / either… or",
    summary: "Paired conjunctions: not only…but also, either…or, neither…nor, both…and; watch inversion after not only.",
    tip_tr: "not only… but also · either… or · neither… nor",
    example: "Not only did she pass, but she also got top marks.",
    difficulty: 4,
    category: "Conjunctions",
  },
  {
    slug: "the-the-comparatives",
    title: "The… the… comparatives",
    summary: "the + comparative, the + comparative shows two things changing together.",
    tip_tr: "The more you practise, the better you get.",
    example: "The sooner we leave, the earlier we'll arrive.",
    difficulty: 4,
    category: "Adjectives",
  },
  {
    slug: "be-supposed-to",
    title: "Be supposed to / be meant to",
    summary: "be supposed to = expected/required (often vs reality); be meant to = intended purpose.",
    tip_tr: "You're supposed to wear a helmet.",
    example: "This film is meant to be funny. I'm supposed to be at work!",
    difficulty: 4,
    category: "Modals",
  },
  {
    slug: "distancing",
    title: "Distancing (seem / appear / apparently)",
    summary: "Use seem/appear, reportedly, apparently, it is said to soften claims and add distance.",
    tip_tr: "It seems that… · She appears to be… · Apparently…",
    example: "He appears to have left. Apparently the meeting was cancelled.",
    difficulty: 4,
    category: "Style",
  },
  {
    slug: "dependent-prepositions",
    title: "Dependent prepositions (advanced)",
    summary: "Noun/adjective/verb + fixed preposition patterns: advantage of, capable of, accuse of, consist of…",
    tip_tr: "aware of · capable of · succeed in · result in",
    example: "She was accused of cheating. Success consists of hard work.",
    difficulty: 4,
    category: "Prepositions",
  },
  {
    slug: "be-about-to-due-to",
    title: "Be about to / due to / to + V",
    summary: "be about to = immediate future; be due to = scheduled; be to = official arrangement.",
    tip_tr: "about to leave · due to arrive · are to report",
    example: "The train is about to leave. She is due to speak at 3.",
    difficulty: 4,
    category: "Tenses",
  },
  {
    slug: "neednt-have-vs-didnt-need",
    title: "Needn't have vs didn't need to",
    summary: "didn't need to = wasn't necessary (maybe not done); needn't have = done but unnecessary.",
    tip_tr: "didn't need to go · needn't have gone (gittim ama gerek yokmuş)",
    example: "I didn't need to cook — there was leftovers. I needn't have cooked so much!",
    difficulty: 4,
    category: "Modals",
  },
  {
    slug: "modal-continuous",
    title: "Modals + continuous / perfect continuous",
    summary: "must/might/should + be + V-ing (now); + have been + V-ing (past duration).",
    tip_tr: "must be joking · might have been waiting",
    example: "She must be studying. He might have been sleeping.",
    difficulty: 4,
    category: "Modals",
  },
  {
    slug: "it-cleft-adj",
    title: "It is + adjective + that / to",
    summary: "It is important/essential/likely that… or to-infinitive to evaluate ideas formally.",
    tip_tr: "It is important that… · It is likely to…",
    example: "It is essential that everyone arrives on time.",
    difficulty: 4,
    category: "Structure",
  },
  {
    slug: "subject-verb-agreement",
    title: "Subject–verb agreement",
    summary: "Agreement with collective nouns, either/neither, each, there is/are, and complex subjects.",
    tip_tr: "The team is/are… · Neither of them is… · There are…",
    example: "Neither option works. The news is surprising.",
    difficulty: 4,
    category: "Structure",
  },

  // ── C1 ──────────────────────────────────────────────────────────────
  {
    slug: "inversion",
    title: "Inversion (negative adverbials)",
    summary: "After never, rarely, not only, under no circumstances… invert auxiliary + subject for emphasis.",
    tip_tr: "Never have I… · Not only did she…",
    example: "Never have I seen such chaos. Rarely does he complain.",
    difficulty: 5,
    category: "Emphasis",
  },
  {
    slug: "subjunctive",
    title: "Subjunctive",
    summary: "Base verb after suggest/recommend/insist that… and in formal phrases (God save…, be that as it may).",
    tip_tr: "I suggest that he go… (bare infinitive)",
    example: "They recommended that she apply early.",
    difficulty: 5,
    category: "Mood",
  },
  {
    slug: "nominalisation",
    title: "Nominalisation",
    summary: "Turn verbs/adjectives into nouns for a more academic, formal style.",
    tip_tr: "decide → decision · develop → development",
    example: "Their decision to expand led to rapid growth.",
    difficulty: 5,
    category: "Style",
  },
  {
    slug: "ellipsis-substitution",
    title: "Ellipsis & substitution",
    summary: "Omit repeated words or replace them with so/do/one to avoid repetition.",
    tip_tr: "I think so. · so do I · a red one",
    example: "She can swim and so can I. I'll take the blue one.",
    difficulty: 5,
    category: "Discourse",
  },
  {
    slug: "emphatic-structures",
    title: "Emphatic structures",
    summary: "do/does/did for emphasis; fronting; rhetorical inversion for style.",
    tip_tr: "I do understand. · Never again will I…",
    example: "I did tell you. What a mess this is!",
    difficulty: 5,
    category: "Emphasis",
  },
  {
    slug: "advanced-modals",
    title: "Advanced modality & hedging",
    summary: "hedges (seem, appear, tend to), probability scales, and formal obligation (be to / be supposed to).",
    tip_tr: "seem to · be supposed to · be to",
    example: "Prices appear to be rising. You are to report by noon.",
    difficulty: 5,
    category: "Modals",
  },
  {
    slug: "hypothesis-speculation",
    title: "Hypothesis & speculation",
    summary: "suppose, imagine, what if, as if/as though, and speculative modals for nuanced meaning.",
    tip_tr: "as if · suppose · might well",
    example: "He talks as if he knew everything. She might well refuse.",
    difficulty: 5,
    category: "Structure",
  },
  {
    slug: "register-formality",
    title: "Register & formality",
    summary: "Choose formal vs informal grammar and vocabulary for academic, professional, or casual contexts.",
    tip_tr: "Could you…? (resmi) · Can you…? (günlük)",
    example: "I would appreciate your assistance. / Can you help?",
    difficulty: 5,
    category: "Style",
  },
  {
    slug: "hedging",
    title: "Hedging language",
    summary: "Softening claims with tend to, suggest, it could be argued, to some extent, arguably…",
    tip_tr: "tend to · suggest that · to some extent · arguably",
    example: "The data suggest that prices may continue to rise.",
    difficulty: 5,
    category: "Style",
  },
  {
    slug: "fronting",
    title: "Fronting & topicalisation",
    summary: "Move an object, adverbial, or complement to the front for emphasis or cohesion.",
    tip_tr: "This problem we can solve. · Into the room walked Ali.",
    example: "Such behaviour I will not tolerate.",
    difficulty: 5,
    category: "Emphasis",
  },
  {
    slug: "absolute-clauses",
    title: "Absolute constructions",
    summary: "Noun + participle/adjective phrase adds a circumstance without a full finite clause.",
    tip_tr: "Her work finished, she left. · Weather permitting,…",
    example: "The exam over, the students cheered.",
    difficulty: 5,
    category: "Clauses",
  },
  {
    slug: "reduced-relative-clauses",
    title: "Reduced relative clauses",
    summary: "Drop who/which/that + be, or use -ing/-ed to shorten defining relatives.",
    tip_tr: "the man sitting there · the book written by her",
    example: "Anyone interested should apply. The people living next door are noisy.",
    difficulty: 5,
    category: "Clauses",
  },
  {
    slug: "parallelism",
    title: "Parallel structure",
    summary: "Keep matching forms in lists and paired constructions (to…, to… / -ing, -ing).",
    tip_tr: "She likes hiking, swimming, and reading. (aynı biçim)",
    example: "The job requires patience, creativity, and attention to detail.",
    difficulty: 5,
    category: "Style",
  },
  {
    slug: "apposition",
    title: "Apposition",
    summary: "Two noun phrases side by side, the second renaming or adding identity to the first.",
    tip_tr: "My friend Ali, a doctor, lives nearby.",
    example: "Istanbul, Turkey's largest city, is vibrant.",
    difficulty: 5,
    category: "Structure",
  },
  {
    slug: "rather-than-instead-of",
    title: "Rather than / instead of",
    summary: "instead of + noun/-ing; rather than often parallels the verb form of the main clause.",
    tip_tr: "instead of waiting · rather than wait/waiting",
    example: "Take a taxi instead of walking. Rather than complain, help.",
    difficulty: 5,
    category: "Conjunctions",
  },
  {
    slug: "perfect-infinitive",
    title: "Perfect infinitive (to have + V3)",
    summary: "appear/seem/claim + to have + V3 for earlier actions; also after modals in perfect form.",
    tip_tr: "seem to have left · claim to have seen",
    example: "She appears to have forgotten. He claimed to have finished.",
    difficulty: 5,
    category: "Verbs",
  },
  {
    slug: "stance-adverbials",
    title: "Stance & comment adverbials",
    summary: "frankly, clearly, surprisingly, in fact, on the whole signal the speaker's attitude.",
    tip_tr: "frankly · clearly · surprisingly · on the whole",
    example: "Frankly, I disagree. Surprisingly, nobody complained.",
    difficulty: 5,
    category: "Discourse",
  },
  {
    slug: "information-structure",
    title: "Given / new information",
    summary: "Put known information early and new focus later; use passives, clefts, and fronting for packaging.",
    tip_tr: "bilinen → baş · yeni bilgi → son (end-focus)",
    example: "The results were published yesterday. It was the CEO who resigned.",
    difficulty: 5,
    category: "Style",
  },
  {
    slug: "verbless-clauses",
    title: "Verbless clauses",
    summary: "Omit be in subordinate circumstances when meaning stays clear (When in Rome…, If necessary…).",
    tip_tr: "If possible… · When young… · Although tired…",
    example: "If necessary, call me. Although exhausted, she smiled.",
    difficulty: 5,
    category: "Clauses",
  },
];

export function getCurriculumTopic(slug: string): CurriculumTopic | undefined {
  return GRAMMAR_CURRICULUM.find((t) => t.slug === slug);
}
