/**
 * Full English grammar syllabus (A1→C1) for the /grammar catalog.
 * Drill items live separately in grammarTopics.ts and merge by slug.
 */

export type CefrBand = 1 | 2 | 3 | 4 | 5; // A1 A2 B1 B2 C1

export type CurriculumTopic = {
  slug: string;
  title: string;
  summary: string;
  tip_tr: string;
  example: string;
  difficulty: CefrBand;
  category: string;
};

export const CEFR_LABEL: Record<CefrBand, string> = {
  1: "A1",
  2: "A2",
  3: "B1",
  4: "B2",
  5: "C1",
};

export const CEFR_SECTION_TITLE: Record<CefrBand, string> = {
  1: "A1 — Temel",
  2: "A2 — Temel üstü",
  3: "B1 — Orta",
  4: "B2 — Orta üstü",
  5: "C1 — İleri",
};

/** Complete topic list shown on /grammar (order = learning path). */
export const GRAMMAR_CURRICULUM: CurriculumTopic[] = [
  // ── A1 ──────────────────────────────────────────────────────────────
  {
    slug: "be-am-is-are",
    title: "To be: am / is / are",
    summary: "Use am with I, is with he/she/it, are with you/we/they for identity, feelings, and location.",
    tip_tr: "I am · he/she/it is · you/we/they are",
    example: "I am a student. She is tired. They are at home.",
    difficulty: 1,
    category: "Verbs",
  },
  {
    slug: "subject-pronouns",
    title: "Subject pronouns",
    summary: "I, you, he, she, it, we, they replace the subject of a sentence.",
    tip_tr: "I / you / he / she / it / we / they",
    example: "Ali is here. He is here.",
    difficulty: 1,
    category: "Pronouns",
  },
  {
    slug: "possessive-adjectives",
    title: "Possessive adjectives",
    summary: "my, your, his, her, its, our, their come before a noun to show ownership.",
    tip_tr: "my book · her name · their car",
    example: "This is my bag. That is her phone.",
    difficulty: 1,
    category: "Pronouns",
  },
  {
    slug: "articles-a-an",
    title: "Articles: a / an",
    summary: "a/an = one (not specific). Use an before a vowel sound.",
    tip_tr: "a book · an apple · an hour (sesli harf sesi)",
    example: "I need a pen and an eraser.",
    difficulty: 1,
    category: "Articles",
  },
  {
    slug: "articles-a-an-the",
    title: "Articles: a / an / the",
    summary: "a/an = one (not specific). the = specific / known to speaker and listener.",
    tip_tr: "a/an = belirsiz · the = belirli",
    example: "I bought an apple and the apple was sweet.",
    difficulty: 1,
    category: "Articles",
  },
  {
    slug: "plurals",
    title: "Plural nouns",
    summary: "Most nouns add -s/-es. Watch irregular plurals (child → children, mouse → mice).",
    tip_tr: "book → books · box → boxes · child → children",
    example: "Two books, three boxes, five children.",
    difficulty: 1,
    category: "Nouns",
  },
  {
    slug: "this-that-these-those",
    title: "Demonstratives: this / that / these / those",
    summary: "this/these = near; that/those = far. this/that singular; these/those plural.",
    tip_tr: "this/these = yakın · that/those = uzak",
    example: "This book is mine. Those cars are expensive.",
    difficulty: 1,
    category: "Determiners",
  },
  {
    slug: "there-is-are",
    title: "There is / there are",
    summary: "Use there is + singular and there are + plural to say something exists.",
    tip_tr: "There is a… · There are two…",
    example: "There is a café nearby. There are many students.",
    difficulty: 1,
    category: "Structure",
  },
  {
    slug: "have-has",
    title: "Have / has",
    summary: "have with I/you/we/they; has with he/she/it for possession.",
    tip_tr: "I have · she has",
    example: "I have a bike. She has two cats.",
    difficulty: 1,
    category: "Verbs",
  },
  {
    slug: "present-simple",
    title: "Present Simple",
    summary: "Use Present Simple for habits, routines, and facts. Add -s/-es with he/she/it.",
    tip_tr: "Alışkanlık ve gerçekler: I work / she works.",
    example: "She goes to school every day.",
    difficulty: 1,
    category: "Tenses",
  },
  {
    slug: "present-simple-neg-q",
    title: "Present Simple: negatives & questions",
    summary: "Negatives and questions use do/does + base verb.",
    tip_tr: "don't/doesn't + V1 · Do/Does + özne + V1?",
    example: "She doesn't like tea. Do you live here?",
    difficulty: 1,
    category: "Tenses",
  },
  {
    slug: "present-continuous",
    title: "Present Continuous",
    summary: "Use am/is/are + verb-ing for actions happening now or around now.",
    tip_tr: "Şu an: am/is/are + V-ing",
    example: "They are playing football right now.",
    difficulty: 1,
    category: "Tenses",
  },
  {
    slug: "can-cant",
    title: "Can / can't (ability & permission)",
    summary: "can + base verb for ability or permission; can't for inability or refusal.",
    tip_tr: "can + V1 · can't = cannot",
    example: "I can swim. Can I open the window?",
    difficulty: 1,
    category: "Modals",
  },
  {
    slug: "imperatives",
    title: "Imperatives",
    summary: "Use the base verb to give orders, requests, and instructions. Don't + verb for negatives.",
    tip_tr: "Open the door. · Don't run.",
    example: "Sit down. Don't touch that.",
    difficulty: 1,
    category: "Structure",
  },
  {
    slug: "in-on-at",
    title: "Prepositions: in / on / at (place)",
    summary: "in = enclosed space; on = surface; at = exact point.",
    tip_tr: "in = içinde · on = üzerinde · at = noktada",
    example: "She is at school. The book is on the table. We live in Ankara.",
    difficulty: 1,
    category: "Prepositions",
  },
  {
    slug: "prepositions-time",
    title: "Prepositions of time",
    summary: "in + months/years/parts of day; on + days/dates; at + clock times / night.",
    tip_tr: "in July · on Monday · at 7 o'clock",
    example: "I was born in 2005. See you on Friday at 6.",
    difficulty: 1,
    category: "Prepositions",
  },
  {
    slug: "wh-questions",
    title: "Wh- questions",
    summary: "who, what, where, when, why, how ask for specific information.",
    tip_tr: "Who / What / Where / When / Why / How",
    example: "Where do you live? Why are you late?",
    difficulty: 1,
    category: "Questions",
  },
  {
    slug: "adjectives-basic",
    title: "Adjectives (basic)",
    summary: "Adjectives describe nouns and usually come before the noun or after be.",
    tip_tr: "a big house · She is happy.",
    example: "It is a cold day. The film was boring.",
    difficulty: 1,
    category: "Adjectives",
  },
  {
    slug: "adverbs-frequency",
    title: "Adverbs of frequency",
    summary: "always, usually, often, sometimes, rarely, never usually go before the main verb (after be).",
    tip_tr: "always → never · be'den sonra, diğer fiilden önce",
    example: "She always arrives early. He is never late.",
    difficulty: 1,
    category: "Adverbs",
  },
  {
    slug: "object-pronouns",
    title: "Object pronouns",
    summary: "me, you, him, her, it, us, them replace the object of a verb or preposition.",
    tip_tr: "me / him / her / us / them",
    example: "Call me. I saw them yesterday.",
    difficulty: 1,
    category: "Pronouns",
  },
  {
    slug: "possessive-s",
    title: "Possessive 's",
    summary: "Add 's to a person/animal to show ownership. Plural ending in s takes only '.",
    tip_tr: "Ali's bag · the students' books",
    example: "This is Sara's phone. The boys' room is tidy.",
    difficulty: 1,
    category: "Nouns",
  },

  // ── A2 ──────────────────────────────────────────────────────────────
  {
    slug: "past-simple",
    title: "Past Simple",
    summary: "Use Past Simple for finished actions in the past. Regular verbs take -ed; many are irregular.",
    tip_tr: "Bitmiş geçmiş: V2 (worked / went)",
    example: "I watched a movie last night.",
    difficulty: 2,
    category: "Tenses",
  },
  {
    slug: "past-simple-irregular",
    title: "Past Simple: irregular verbs",
    summary: "Common irregulars: go→went, see→saw, have→had, make→made, take→took.",
    tip_tr: "go–went · see–saw · take–took · make–made",
    example: "She went home. He took the bus.",
    difficulty: 2,
    category: "Tenses",
  },
  {
    slug: "past-continuous",
    title: "Past Continuous",
    summary: "was/were + V-ing for an action in progress at a past moment (often interrupted).",
    tip_tr: "was/were + V-ing",
    example: "I was cooking when she called.",
    difficulty: 2,
    category: "Tenses",
  },
  {
    slug: "going-to",
    title: "Future: be going to",
    summary: "am/is/are + going to + verb for plans and predictions from present evidence.",
    tip_tr: "be + going to + V1",
    example: "I'm going to study tonight. Look at those clouds — it's going to rain.",
    difficulty: 2,
    category: "Tenses",
  },
  {
    slug: "will-future",
    title: "Future: will",
    summary: "will + base verb for instant decisions, offers, promises, and predictions.",
    tip_tr: "will + V1 · won't = will not",
    example: "I'll help you. It will be sunny tomorrow.",
    difficulty: 2,
    category: "Tenses",
  },
  {
    slug: "present-continuous-future",
    title: "Present Continuous for future",
    summary: "am/is/are + V-ing for fixed personal arrangements in the near future.",
    tip_tr: "Yarınki randevu: I'm meeting Ali at 5.",
    example: "We're flying to Izmir on Friday.",
    difficulty: 2,
    category: "Tenses",
  },
  {
    slug: "present-perfect",
    title: "Present Perfect",
    summary: "have/has + past participle for life experience and actions linked to now (for/since).",
    tip_tr: "have/has + V3 · for / since",
    example: "She has lived in London since 2010.",
    difficulty: 2,
    category: "Tenses",
  },
  {
    slug: "present-perfect-vs-past",
    title: "Present Perfect vs Past Simple",
    summary: "Present Perfect = unfinished time / result now. Past Simple = finished time (yesterday, in 2019).",
    tip_tr: "ever/never/just → Perfect · yesterday/last… → Past",
    example: "I have seen that film. I saw it last week.",
    difficulty: 2,
    category: "Tenses",
  },
  {
    slug: "comparatives",
    title: "Comparatives",
    summary: "Compare two things: adj + -er + than, or more + adj + than for longer adjectives.",
    tip_tr: "taller than · more interesting than · better/worse",
    example: "This bag is cheaper than that one.",
    difficulty: 2,
    category: "Adjectives",
  },
  {
    slug: "superlatives",
    title: "Superlatives",
    summary: "the + adj-est or the most + adj to say something is number one in a group.",
    tip_tr: "the tallest · the most expensive · the best",
    example: "She is the fastest runner in the class.",
    difficulty: 2,
    category: "Adjectives",
  },
  {
    slug: "countable-uncountable",
    title: "Countable & uncountable nouns",
    summary: "Countable have singular/plural (a book / books). Uncountable have no plural (water, advice, information).",
    tip_tr: "a/an/many + sayıla bilir · much/some + sayılamaz",
    example: "I need some water and two apples.",
    difficulty: 2,
    category: "Nouns",
  },
  {
    slug: "some-any-much-many",
    title: "Some / any / much / many",
    summary: "some (positive), any (questions/negatives); many + countable, much + uncountable.",
    tip_tr: "some (+) · any (?/–) · many books · much time",
    example: "Do you have any sugar? I don't have much time.",
    difficulty: 2,
    category: "Quantifiers",
  },
  {
    slug: "modals-obligation",
    title: "Must / have to / should",
    summary: "must/have to = obligation; should = advice; mustn't = prohibition; don't have to = no need.",
    tip_tr: "must/have to = zorunluluk · should = tavsiye",
    example: "You should sleep more. You mustn't smoke here.",
    difficulty: 2,
    category: "Modals",
  },
  {
    slug: "could-would",
    title: "Could / would",
    summary: "could = past ability / polite request; would like = polite want; would = hypothetical.",
    tip_tr: "Could you…? · I'd like… · I could swim (geçmiş)",
    example: "Could you help me? I'd like a coffee.",
    difficulty: 2,
    category: "Modals",
  },
  {
    slug: "first-conditional",
    title: "First conditional",
    summary: "If + Present Simple, will + verb for real future possibilities.",
    tip_tr: "If it rains, I will stay home.",
    example: "If you study, you will pass.",
    difficulty: 2,
    category: "Conditionals",
  },
  {
    slug: "gerunds-infinitives",
    title: "Gerunds & infinitives",
    summary: "Some verbs take -ing (enjoy swimming); others take to + verb (want to go).",
    tip_tr: "enjoy + V-ing · want + to V",
    example: "I enjoy reading. She wants to travel.",
    difficulty: 2,
    category: "Verbs",
  },
  {
    slug: "relative-who-which",
    title: "Relative pronouns: who / which / that",
    summary: "who = people; which = things; that = people or things in defining clauses.",
    tip_tr: "who = kişi · which = şey · that = ikisi",
    example: "The man who called is my teacher.",
    difficulty: 2,
    category: "Clauses",
  },
  {
    slug: "articles-the",
    title: "Articles: the (specific use)",
    summary: "the for unique things, second mention, superlatives, and known shared context.",
    tip_tr: "the sun · the first one · the same café",
    example: "The moon is bright tonight.",
    difficulty: 2,
    category: "Articles",
  },
  {
    slug: "adverbs-manner",
    title: "Adverbs of manner",
    summary: "Many adverbs add -ly to adjectives (quick → quickly) and say how something happens.",
    tip_tr: "slow → slowly · careful → carefully · fast/hard (aynı)",
    example: "She speaks English clearly.",
    difficulty: 2,
    category: "Adverbs",
  },
  {
    slug: "used-to",
    title: "Used to",
    summary: "used to + verb for past habits or states that are no longer true.",
    tip_tr: "used to + V1 (eskiden … yapardım)",
    example: "I used to play tennis every week.",
    difficulty: 2,
    category: "Tenses",
  },

  // ── B1 ──────────────────────────────────────────────────────────────
  {
    slug: "present-perfect-continuous",
    title: "Present Perfect Continuous",
    summary: "have/has been + V-ing for actions that started in the past and continue, or just stopped with a visible result.",
    tip_tr: "have/has been + V-ing",
    example: "I have been waiting for an hour.",
    difficulty: 3,
    category: "Tenses",
  },
  {
    slug: "past-perfect",
    title: "Past Perfect",
    summary: "had + V3 for an action completed before another past action.",
    tip_tr: "had + V3 (önce bitmiş geçmiş)",
    example: "She had left before I arrived.",
    difficulty: 3,
    category: "Tenses",
  },
  {
    slug: "past-perfect-continuous",
    title: "Past Perfect Continuous",
    summary: "had been + V-ing for a continuous action before a past point.",
    tip_tr: "had been + V-ing",
    example: "He had been working all day before the meeting.",
    difficulty: 3,
    category: "Tenses",
  },
  {
    slug: "future-continuous",
    title: "Future Continuous",
    summary: "will be + V-ing for an action in progress at a future time.",
    tip_tr: "will be + V-ing",
    example: "This time tomorrow I will be flying to Rome.",
    difficulty: 3,
    category: "Tenses",
  },
  {
    slug: "future-perfect",
    title: "Future Perfect",
    summary: "will have + V3 for an action completed before a future deadline.",
    tip_tr: "will have + V3",
    example: "By Friday I will have finished the report.",
    difficulty: 3,
    category: "Tenses",
  },
  {
    slug: "second-conditional",
    title: "Second conditional",
    summary: "If + Past Simple, would + verb for unreal or unlikely present/future situations.",
    tip_tr: "If I were rich, I would travel.",
    example: "If I had more time, I would learn piano.",
    difficulty: 3,
    category: "Conditionals",
  },
  {
    slug: "third-conditional",
    title: "Third conditional",
    summary: "If + Past Perfect, would have + V3 for unreal past (regret / different past).",
    tip_tr: "If I had studied, I would have passed.",
    example: "If she had left earlier, she would have caught the train.",
    difficulty: 3,
    category: "Conditionals",
  },
  {
    slug: "passive-voice",
    title: "Passive voice",
    summary: "be + V3 when the focus is on the action/result, not the doer (by + agent optional).",
    tip_tr: "be + V3 · The letter was sent.",
    example: "English is spoken here. The cake was made by Tom.",
    difficulty: 3,
    category: "Voice",
  },
  {
    slug: "reported-speech",
    title: "Reported speech",
    summary: "Backshift tenses when reporting past statements; change pronouns and time words.",
    tip_tr: "am → was · will → would · today → that day",
    example: "She said she was tired. He told me he would call.",
    difficulty: 3,
    category: "Speech",
  },
  {
    slug: "relative-clauses",
    title: "Relative clauses",
    summary: "Defining clauses identify the noun; non-defining add extra info and use commas.",
    tip_tr: "tanımlayan (virgülsüz) · ek bilgi (virgüllü)",
    example: "My brother, who lives in Berlin, is a doctor.",
    difficulty: 3,
    category: "Clauses",
  },
  {
    slug: "modals-deduction",
    title: "Modals of deduction",
    summary: "must = certainty; might/may/could = possibility; can't = impossibility (about now).",
    tip_tr: "must be · might be · can't be",
    example: "He must be at work. That can't be true.",
    difficulty: 3,
    category: "Modals",
  },
  {
    slug: "wish-if-only",
    title: "Wish / if only",
    summary: "wish + Past Simple (present regret); wish + Past Perfect (past regret); wish + would (annoyance).",
    tip_tr: "I wish I knew · I wish I had gone",
    example: "I wish I spoke French. If only I had listened.",
    difficulty: 3,
    category: "Structure",
  },
  {
    slug: "so-such",
    title: "So / such",
    summary: "so + adjective/adverb; such + (a/an) + adjective + noun for emphasis.",
    tip_tr: "so tired · such a long day",
    example: "It was so cold. It was such a cold night.",
    difficulty: 3,
    category: "Intensifiers",
  },
  {
    slug: "enough-too",
    title: "Enough / too",
    summary: "too = more than wanted; enough = as much as needed (adj + enough / enough + noun).",
    tip_tr: "too heavy · tall enough · enough money",
    example: "This bag is too heavy. I'm not tall enough.",
    difficulty: 3,
    category: "Quantifiers",
  },
  {
    slug: "both-either-neither",
    title: "Both / either / neither",
    summary: "both = the two; either = one or the other; neither = not one and not the other.",
    tip_tr: "both of them · either option · neither works",
    example: "Both answers are correct. Neither team scored.",
    difficulty: 3,
    category: "Determiners",
  },
  {
    slug: "quantifiers",
    title: "Quantifiers (few / little / plenty)",
    summary: "a few/few + countable; a little/little + uncountable; plenty of = more than enough.",
    tip_tr: "a few friends · little time · plenty of food",
    example: "I have a few ideas but little money.",
    difficulty: 3,
    category: "Quantifiers",
  },
  {
    slug: "linking-words",
    title: "Linking words",
    summary: "although, however, therefore, because, so, while connect ideas logically.",
    tip_tr: "although / however / therefore / because",
    example: "Although it rained, we went out.",
    difficulty: 3,
    category: "Discourse",
  },
  {
    slug: "phrasal-verbs",
    title: "Phrasal verbs",
    summary: "Verb + particle with a special meaning (look up, give up, turn on). Some are separable.",
    tip_tr: "look up · give up · turn on (ayrılabilir olanlar)",
    example: "Please turn the lights off. She gave up smoking.",
    difficulty: 3,
    category: "Vocabulary",
  },

  // ── B2 ──────────────────────────────────────────────────────────────
  {
    slug: "mixed-conditionals",
    title: "Mixed conditionals",
    summary: "Mix past and present unreal forms: past cause → present result, or present condition → past result.",
    tip_tr: "If I had…, I would be… (geçmiş → şimdi)",
    example: "If I had studied medicine, I would be a doctor now.",
    difficulty: 4,
    category: "Conditionals",
  },
  {
    slug: "causative",
    title: "Causative: have / get something done",
    summary: "have/get + object + V3 when someone else does the action for you.",
    tip_tr: "have/get + nesne + V3",
    example: "I had my hair cut. She got her car repaired.",
    difficulty: 4,
    category: "Structure",
  },
  {
    slug: "advanced-passive",
    title: "Advanced passive",
    summary: "Passive with modals, reporting verbs (it is said that…), and get-passive.",
    tip_tr: "It is said that… · The window got broken.",
    example: "It is believed that the company will expand.",
    difficulty: 4,
    category: "Voice",
  },
  {
    slug: "reported-questions",
    title: "Reported questions & commands",
    summary: "No do-support; use if/whether for yes-no; ask/tell + object + to-infinitive for commands.",
    tip_tr: "He asked where I lived. · She told me to wait.",
    example: "She asked if I was ready. He told us to sit down.",
    difficulty: 4,
    category: "Speech",
  },
  {
    slug: "modals-perfect",
    title: "Modals + perfect infinitive",
    summary: "must/might/should/could + have + V3 for past deduction, advice, and possibility.",
    tip_tr: "must have · should have · could have",
    example: "You should have called. He must have forgotten.",
    difficulty: 4,
    category: "Modals",
  },
  {
    slug: "future-in-the-past",
    title: "Future in the past",
    summary: "was/were going to, would, was about to for planned or expected future from a past viewpoint.",
    tip_tr: "was going to · would · was about to",
    example: "I was going to call, but my phone died.",
    difficulty: 4,
    category: "Tenses",
  },
  {
    slug: "participle-clauses",
    title: "Participle clauses",
    summary: "Use -ing / -ed clauses to shorten relative or adverbial clauses.",
    tip_tr: "Walking home, I met Ali. · Built in 1900,…",
    example: "Feeling tired, she went to bed early.",
    difficulty: 4,
    category: "Clauses",
  },
  {
    slug: "relative-advanced",
    title: "Advanced relative clauses",
    summary: "whose, where, when, why; preposition + which/whom; reduced relatives.",
    tip_tr: "whose · of which · the man I met",
    example: "The woman whose car was stolen called the police.",
    difficulty: 4,
    category: "Clauses",
  },
  {
    slug: "inversion-conditionals",
    title: "Inversion in conditionals",
    summary: "Formal: Had I known… / Were I you… / Should you need… instead of if-clauses.",
    tip_tr: "Had I known… = If I had known…",
    example: "Had I known, I would have helped.",
    difficulty: 4,
    category: "Conditionals",
  },
  {
    slug: "cleft-sentences",
    title: "Cleft sentences",
    summary: "It is/was … that/who and What … is/was to emphasize one part of a sentence.",
    tip_tr: "It was Ali who called. · What I need is rest.",
    example: "It was yesterday that we met.",
    difficulty: 4,
    category: "Emphasis",
  },
  {
    slug: "discourse-markers",
    title: "Discourse markers",
    summary: "anyway, actually, on the other hand, in contrast, furthermore structure spoken and written argument.",
    tip_tr: "however · furthermore · on the other hand",
    example: "On the other hand, costs may rise.",
    difficulty: 4,
    category: "Discourse",
  },
  {
    slug: "noun-phrases",
    title: "Complex noun phrases",
    summary: "Stack determiners, adjectives, and of-phrases to pack information into one noun group.",
    tip_tr: "the sudden rise in prices · a well-known expert",
    example: "The rapid growth of online shopping surprised analysts.",
    difficulty: 4,
    category: "Nouns",
  },

  // ── C1 ──────────────────────────────────────────────────────────────
  {
    slug: "inversion",
    title: "Inversion (negative adverbials)",
    summary: "After never, rarely, not only, under no circumstances… invert auxiliary + subject for emphasis.",
    tip_tr: "Never have I… · Not only did she…",
    example: "Never have I seen such chaos. Rarely does he complain.",
    difficulty: 5,
    category: "Emphasis",
  },
  {
    slug: "subjunctive",
    title: "Subjunctive",
    summary: "Base verb after suggest/recommend/insist that… and in formal phrases (God save…, be that as it may).",
    tip_tr: "I suggest that he go… (bare infinitive)",
    example: "They recommended that she apply early.",
    difficulty: 5,
    category: "Mood",
  },
  {
    slug: "nominalisation",
    title: "Nominalisation",
    summary: "Turn verbs/adjectives into nouns for a more academic, formal style.",
    tip_tr: "decide → decision · develop → development",
    example: "Their decision to expand led to rapid growth.",
    difficulty: 5,
    category: "Style",
  },
  {
    slug: "ellipsis-substitution",
    title: "Ellipsis & substitution",
    summary: "Omit repeated words or replace them with so/do/one to avoid repetition.",
    tip_tr: "I think so. · so do I · a red one",
    example: "She can swim and so can I. I'll take the blue one.",
    difficulty: 5,
    category: "Discourse",
  },
  {
    slug: "emphatic-structures",
    title: "Emphatic structures",
    summary: "do/does/did for emphasis; fronting; rhetorical inversion for style.",
    tip_tr: "I do understand. · Never again will I…",
    example: "I did tell you. What a mess this is!",
    difficulty: 5,
    category: "Emphasis",
  },
  {
    slug: "advanced-modals",
    title: "Advanced modality & hedging",
    summary: "hedges (seem, appear, tend to), probability scales, and formal obligation (be to / be supposed to).",
    tip_tr: "seem to · be supposed to · be to",
    example: "Prices appear to be rising. You are to report by noon.",
    difficulty: 5,
    category: "Modals",
  },
  {
    slug: "hypothesis-speculation",
    title: "Hypothesis & speculation",
    summary: "suppose, imagine, what if, as if/as though, and speculative modals for nuanced meaning.",
    tip_tr: "as if · suppose · might well",
    example: "He talks as if he knew everything. She might well refuse.",
    difficulty: 5,
    category: "Structure",
  },
  {
    slug: "register-formality",
    title: "Register & formality",
    summary: "Choose formal vs informal grammar and vocabulary for academic, professional, or casual contexts.",
    tip_tr: "Could you…? (resmi) · Can you…? (günlük)",
    example: "I would appreciate your assistance. / Can you help?",
    difficulty: 5,
    category: "Style",
  },
];

export function getCurriculumTopic(slug: string): CurriculumTopic | undefined {
  return GRAMMAR_CURRICULUM.find((t) => t.slug === slug);
}
